// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydlfkbryztpbmemuwule.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkbGZrYnJ5enRwYm1lbXV3dWxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MjI1MzksImV4cCI6MjA2MDA5ODUzOX0.AaTX9QegdK3M61geZQD2ciaihly5ESWYcBuwmzrvU1U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);